name: Secret Key
run-name: ${{github.actor}} requesting access token
on: [push]

jobs:
  retrieving-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Key
        # with:
        #   super_secret: ${{ secrets.GIT_KEY }}
        env: 
          GIT_KEY: ${{ secrets.GIT_KEY }}
        run: |
          echo "$GIT_KEY" > "$GITHUB_WORKSPACE/secrets.txt"
          echo "$GITHUB_CONTEXT"
      
      - uses: actions/upload-artifact@v4
        uses: actions/setup-node@v4
        name: Upload Artifact
        with:
          name: SecretsVariables
          node-version: '20'
          path: ${{ github.workspace }}/secrets.txt
