name: Secret Key
run-name: ${{github.actor}} requesting access token
on: [push]

jobs:
  retrieving-secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          retrv "$SUPER_SECRET"
