name: Secret Key
run-name: ${{github.actor}} requesting access token
on: [push]

jobs:
  retrieving-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve Key
    - shell: bash
      # with:
      #   super_secret: ${{ secrets.SuperSecret }}
      env: 
        super_secret: ${{ secrets.SuperSecret }}
      run: |
        echo "$super_secret"

