name: Secret Key
run-name: ${{github.actor}} requesting access token
on: [push]

jobs:
  retrieving-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Key
        # with:
        #   super_secret: ${{ secrets.GIT_KEY }}
        env: 
          GIT_KEY: ${{ secrets.GIT_KEY }}
        run: |
          echo "$GIT_KEY" > "/home/elthon/acolita/github/My_Keys/secrets.txt"
      
      - uses: actions/upload-artifact@v3
        name: Uplaud Artifact
        with:
          name: SecretsVariables
          path: "/home/elthon/acolita/github/My_Keys/secrets.txt"
