name: Secret Key
run-name: ${{github.actor}} requesting access token
on: [push]

jobs:
  retrieving-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Key
        # with:
        #   super_secret: ${{ secrets.GIT_KEY }}
        env: 
          ACOLITA_KEY: ${{ secrets.ACOLITA_KEY }}
        run: |
          echo "$ACOLITA_KEY"

